# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Our Home Connected add-on"
  org.opencontainers.image.description: "Version control on automations and scripts with Github."
  org.opencontainers.image.source: "https://github.com/danieldotnl/addons-ourhomeconnected"
  org.opencontainers.image.licenses: "GPL-3.0"
args:
  TEMPIO_VERSION: "2021.09.0"
  WHEEL_VERSION: "0.1.6"
