# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Our Home Connected add-on
version: "1.0.0"
slug: ourhomeconnected
description: Our Home Connected add-on
url: "https://github.com/home-assistant/addons-ourhomeconnected/tree/main/ourhomeconnected"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/danieldotnl/{arch}-addon-ourhomeconnected"
