# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Our Home Connected add-on
version: "2.0.0"
slug: ourhomeconnected
description: Our Home Connected add-on
url: "https://github.com/home-assistant/addons-ourhomeconnected/tree/main/ourhomeconnected"
arch:
  - aarch64
  - amd64
init: false
ports:
  8000/tcp: 8000
ingress: true
ingress_port: 8000
panel_icon: mdi:git
panel_title: "OHC"
homeassistant_api: true
environment:
  ENVIRONMENT: "prod"
map:
  - share:rw
options:
  message: "Hello world..."
  log_level: info
schema:
  message: "str?"
  log_level: list(trace|debug|info|warning|error|fatal)
image: "ghcr.io/danieldotnl/{arch}-addon-ourhomeconnected"
